### PR TITLE
feat: Removing unnecessary software upgrade handlers

### PR DESCRIPTION
**Pull request by pbukva**

### CODE REVIEW

**Review by MissingNO57 — APPROVED** [review]
LGTM

**Review by Jonathansumner — APPROVED** [review]
Lgtm, bud!

**Comment by pbukva** [comment]
Strictly speaking, the software upgrade handler is not required when starting fresh eon - starting from fresh genesis with erased node databases.

**Comment by pbukva** [comment]
As per note above, we went with simplest possible way - dropping everthing what is not necessary = all upgrade handlers have been removed.

**Pull request merged**
